openapi: 3.0.0
info:
  title: Adressbuch
  description: "Die Adressbuch-App nutzt einen simplen REST-Webservices zur Kommunikation\
    \ mit dem Backend. Dieser ermöglicht die üblichen CRUD-Operationen zur Suche,\
    \ Anzeige, Bearbeitung und Löschung von Adressen, wobei jede Adresse aus einem\
    \ Vornamen, Nachnamen, Telefonnummer und eine E-Mailadresse besteht."
  contact:
    name: Dennis Schulmeister-Zimolong
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Adresse
paths:
  /address:
    get:
      tags:
      - Adresse
      summary: Adressen suchen
      description: Suche nach Adressen. Gibt eine Liste aller Adressen passend zu
        den übergebenen Suchkriterien zurück.
      operationId: search-address
      parameters:
      - name: first_name
        in: query
        description: Vorname
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: last_name
        in: query
        description: Nachname
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Address'
                x-content-type: application/json
      x-swagger-router-controller: Adresse
    post:
      tags:
      - Adresse
      summary: Adresse anlegen
      description: "Neue Adresse anlegen. Speichert die übergebene Adresse in der\
        \ Datenbank. Der Wert des Feldes \"id\" wird dabei ignorier, da in jedem Fall\
        \ eine neue Adresse mit neuer ID angelegt wird."
      operationId: create-address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        "400":
          description: Bad Request (Vorname oder Nachname fehlt)
      x-swagger-router-controller: Adresse
  /address/{id}:
    get:
      tags:
      - Adresse
      summary: Adresse lesen
      description: Liest eine einzelne Adresse vom Server.
      operationId: get-address
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        "404":
          description: Not Found
      x-swagger-router-controller: Adresse
    put:
      tags:
      - Adresse
      summary: ""
      description: "Überschreibt eine vorhandene Adresse auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      operationId: update-address
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        "400":
          description: Bad Request (Vorname oder Nachname fehlt)
        "404":
          description: Not Found
      x-swagger-router-controller: Adresse
    delete:
      tags:
      - Adresse
      summary: Adresse löschen
      description: Löscht eine Adresse auf dem Server.
      operationId: delete-address
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      x-swagger-router-controller: Adresse
    patch:
      tags:
      - Adresse
      summary: Einzelne Adressfelder ändern
      description: "Ändert einzelne Felder einer vorhandenen Adresse. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      operationId: patch-address
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      x-swagger-router-controller: Adresse
components:
  schemas:
    Address:
      title: Adresse
      type: object
      properties:
        id:
          type: string
          readOnly: true
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
      example:
        phone: phone
        last_name: last_name
        id: id
        first_name: first_name
        email: ""
  securitySchemes: {}
