openapi: 3.0.0
info:
  title: MyAPP
  description: "__ TODO: Diese Datei durch eine eigene API-Spezifikation ersetzen. __"
  contact:
    name: Dennis Schulmeister-Zimolong
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Beispiel
paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      operationId: index
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

  /example:
    get:
      tags:
      - Beispiel
      summary: Beispiele suchen
      description: Suche nach Beispielen. Gibt eine Liste aller Beispieele passend zu
        den übergebenen Suchkriterien zurück.
      operationId: search-ExampleController
      parameters:
      - name: title
        in: query
        description: Titel
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: author
        in: query
        description: Autor
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'
                x-content-type: application/json
    post:
      tags:
      - Beispiel
      summary: Beispiel anlegen
      description: "Neues Beispiel anlegen. Speichert das übergebene Beispiel in der\
        \ Datenbank. Der Wert des Feldes \"_id\" wird dabei ignoriert, da in jedem Fall\
        \ eine neue Beispiel mit neuer ID angelegt wird."
      operationId: create-address
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Example'
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
  /example/{id}:
    get:
      tags:
      - Beispiel
      summary: Beispiel lesen
      description: Liest ein einzelnes Beispiel vom Server.
      operationId: get-example
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        "404":
          description: Not Found
    put:
      tags:
      - Beispiel
      summary: ""
      description: "Überschreibt ein vorhandenes Beispiel auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      operationId: update-example
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Example'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        "404":
          description: Not Found
    delete:
      tags:
      - Beispiel
      summary: Beispiel löschen
      description: Löscht ein Beispiel auf dem Server.
      operationId: delete-example
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
    patch:
      tags:
      - Beispiel
      summary: Einzelne Beispielfelder ändern
      description: "Ändert einzelne Felder eines vorhandenen Beispiels. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      operationId: patch-example
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Example'
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
components:
  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string

    Address:
      title: Example
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        year:
          type: integer
      required:
        - title
        - author
      example:
        _id: "621ff9a936997df5baba746e"
        title: "Advanced API Security"
        author: "Prabath Siriwardena"
        publisher: "Apress"
        year: 2020
  securitySchemes: {}
