openapi: 3.0.0
info:
  title: "Aufgabe: Hey, Mr. Postman"
  description: "Dieser Webservice dient dazu, die typischen HTTP-Aufrufe bei \
    \ Verwendung eines REST-Webservices mit einem Werkzeug wie Postman (https://www.postman.com/) \
    \ auszuprobieren. Hierfür wird eine simple API zur Verwaltung von Songs angeboten."
  contact:
    name: Dennis Schulmeister-Zimolong
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Index
- name: Song

paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

  /song:
    get:
      tags:
        - Song
      summary: Song-Collection
      description: Eine Liste von Songs
      parameters:
      - name: search
        in: query
        required: false
        description: Suchbegriff (alle anderen Parameter werden dann ignoriert)
        schema:
          type: string
      - name: artist
        in: query
        required: false
        description: Künstler (exakte Übereinstimmung)
        schema:
          type: string
      - name: name
        in: query
        required: false
        description: Songname (exakte Übereinstimmung)
        schema:
          type: string
      - name: releaseYear
        in: query
        required: false
        description: Jahr der Veröffentlichung (exakte Übereinstimmung)
        schema:
          type: integer
      - name: songwriters
        in: query
        required: false
        description: Songschreiber (exakte Übereinstimmung)
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Song'
                x-content-type: application/json

  /song/{id}:
    get:
      tags:
      - Song
      summary: Song lesen
      description: Liest einen einzelnen Song vom Server.
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
        "404":
          description: Not Found
    put:
      tags:
      - Song
      summary: ""
      description: "Überschreibt einen vorhandenen Song auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
        "404":
          description: Not Found
    delete:
      tags:
      - Song
      summary: Song löschen
      description: Löscht einen Song auf dem Server.
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
    patch:
      tags:
      - Song
      summary: Einzelne Songfelder ändern
      description: "Ändert einzelne Felder eines vorhandenen Songs. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
      responses:
        "200":
          description: OK
        "404":
          description: Not Found

components:
  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string

    Song:
      title: Song
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        artist:
          type: string
        name:
          type: string
        release_year:
          type: integer
        songwriters:
          type: string
      required:
        - name
      example:
        _id: "621ff9a936997df5baba746e"
        artist: "Elton John"
        name: "Circle of Life"
        release_year: 1994
        songwriters: "Tim Rice"

  securitySchemes: {}
